ANNOTATION_CONFIG = {
    "bodyPart": {"Head": {"index": 0, "annotationParts": [
        {"name": "thalamic transverse plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Genu of Corpus Callosum", "alias": "", "color": "31,0,255,25"},
                    {"name": "Splenium of Corpus Callosum", "alias": "", "color": "0,159,255,25"},
                    {"name": "Body of Corpus Callosum", "alias": "", "color": "255,95,0,25"},
                    {"name": "Cerebellum", "alias": "", "color": "255,0,0,25"},
                    {"name": "cerebellar hemisphere", "alias": "", "color": "0,255,25,25"},
                    {"name": "Midbrain", "alias": "", "color": "255,0,133,25"},
                    {"name": "Body of Lateral Ventricle", "alias": "", "color": "255,172,0,25"},
                    {"name": "skull Halo", "alias": "", "color": "108,0,255,25"},
                    {"name": "Falx Cerebri", "alias": "", "color": "0,82,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "0,255,6,25"},
                    {"name": "thalamic", "alias": "", "color": "255,0,152,25"},
                    {"name": "Third Ventricle", "alias": "", "color": "223,0,255,25"},
                    {"name": "posterior horn of the lateral ventricle", "alias": "", "color": "12,0,255,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "0,255,178,25"},
                    {"name": "choroid plexus", "alias": "", "color": "108,255,0,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "184,0,255,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "255,0,76,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "146,255,0,25"},
                    {"name": "Superior Temporal Sulcus", "alias": "", "color": "51,0,255,25"},
                    {"name": "Inferior Temporal Sulcus", "alias": "", "color": "0,197,255,25"},
                    {"name": "Cingulate Sulcus", "alias": "", "color": "255,248,0,25"},
                    {"name": "Column of Fornix", "alias": "", "color": "255,0,19,25"},
                    {"name": "Superior Frontal Sulcus", "alias": "", "color": "89,255,0,25"},
                    {"name": "Parietooccipital Sulcus", "alias": "", "color": "127,255,0,25"},
                    {"name": "Calcarine Sulcus", "alias": "", "color": "255,153,0,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "0,255,255,25"},
                    {"name": "Insula", "alias": "", "color": "0,255,121,25"},
                    {"name": "Inferior Frontal Sulcus", "alias": "", "color": "255,0,248,25"},
                    {"name": "Head of Caudate Nucleus", "alias": "", "color": "70,0,255,25"},
                    {"name": "Cerebellar Fissure", "alias": "", "color": "244,254,255,25"},
                    {"name": "Cerebral Aqueduct", "alias": "", "color": "255,0,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "lateral ventricular transverse plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "skull Halo", "alias": "", "color": "31,0,255,25"},
                    {"name": "Falx Cerebri", "alias": "", "color": "0,159,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "255,95,0,25"},
                    {"name": "thalamic", "alias": "", "color": "255,0,0,25"},
                    {"name": "Third Ventricle", "alias": "", "color": "0,255,25,25"},
                    {"name": "posterior horn of the lateral ventricle", "alias": "", "color": "255,0,133,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,172,0,25"},
                    {"name": "choroid plexus", "alias": "", "color": "108,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,82,255,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "0,255,6,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "255,0,152,25"},
                    {"name": "Superior Temporal Sulcus", "alias": "", "color": "223,0,255,25"},
                    {"name": "Inferior Temporal Sulcus", "alias": "", "color": "12,0,255,25"},
                    {"name": "Cingulate Sulcus", "alias": "", "color": "0,255,178,25"},
                    {"name": "Column of Fornix", "alias": "", "color": "108,255,0,25"},
                    {"name": "Superior Frontal Sulcus", "alias": "", "color": "184,0,255,25"},
                    {"name": "Parietooccipital Sulcus", "alias": "", "color": "255,0,76,25"},
                    {"name": "Calcarine Sulcus", "alias": "", "color": "146,255,0,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "51,0,255,25"},
                    {"name": "Insula", "alias": "", "color": "0,197,255,25"},
                    {"name": "Genu of Corpus Callosum", "alias": "", "color": "255,248,0,25"},
                    {"name": "Splenium of Corpus Callosum", "alias": "", "color": "255,0,19,25"},
                    {"name": "Body of Corpus Callosum", "alias": "", "color": "89,255,0,25"},
                    {"name": "Midbrain", "alias": "", "color": "127,255,0,25"},
                    {"name": "Body of Lateral Ventricle", "alias": "", "color": "255,153,0,25"},
                    {"name": "Cerebellum", "alias": "", "color": "0,255,255,25"},
                    {"name": "Inferior Frontal Sulcus", "alias": "", "color": "0,255,121,25"},
                    {"name": "Head of Caudate Nucleus", "alias": "", "color": "255,0,248,25"},
                    {"name": "Cavum Veli Interpositi", "alias": "", "color": "44,255,7,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "cerebellar transverse plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "skull Halo", "alias": "", "color": "31,0,255,25"},
                    {"name": "Falx Cerebri", "alias": "", "color": "0,159,255,25"},
                    {"name": "cerebellar hemisphere", "alias": "", "color": "255,95,0,25"},
                    {"name": "Vermis of Cerebellum", "alias": "", "color": "255,0,0,25"},
                    {"name": "Fourth Ventricle", "alias": "", "color": "0,255,25,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "255,0,133,25"},
                    {"name": "Midbrain", "alias": "", "color": "255,172,0,25"},
                    {"name": "thalamic", "alias": "", "color": "108,0,255,25"},
                    {"name": "Third Ventricle", "alias": "", "color": "0,82,255,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "0,255,6,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "255,0,152,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "223,0,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "12,0,255,25"},
                    {"name": "Superior Temporal Sulcus", "alias": "", "color": "0,255,178,25"},
                    {"name": "Inferior Temporal Sulcus", "alias": "", "color": "108,255,0,25"},
                    {"name": "Cingulate Sulcus", "alias": "", "color": "184,0,255,25"},
                    {"name": "Column of Fornix", "alias": "", "color": "255,0,76,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "146,255,0,25"},
                    {"name": "Insula", "alias": "", "color": "51,0,255,25"},
                    {"name": "Hippocampus", "alias": "", "color": "0,197,255,25"},
                    {"name": "Tentorium Cerebelli", "alias": "", "color": "255,248,0,25"},
                    {"name": "Superior Frontal Sulcus", "alias": "", "color": "255,0,19,25"},
                    {"name": "Inferior Frontal Sulcus", "alias": "", "color": "89,255,0,25"},
                    {"name": "Cerebral Aqueduct", "alias": "", "color": "127,255,0,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "255,153,0,25"},
                    {"name": "Body of Lateral Ventricle", "alias": "", "color": "0,255,255,25"},
                    {"name": "Genu of Corpus Callosum", "alias": "", "color": "0,255,121,25"},
                    {"name": "Splenium of Corpus Callosum", "alias": "", "color": "255,0,248,25"},
                    {"name": "Body of Corpus Callosum", "alias": "", "color": "70,0,255,25"},
                    {"name": "posterior horn of the lateral ventricle", "alias": "", "color": "0,255,159,25"},
                    {"name": "choroid plexus", "alias": "", "color": "0,216,255,25"},
                    {"name": "Inferior Horn", "alias": "", "color": "0,6,255,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "0,63,255,25"},
                    {"name": "Cerebellomedullary Cistern", "alias": "", "color": "255,153,0,25"},
                    {"name": "Cerebellar Fissure", "alias": "", "color": "255,0,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Transverse Plane of Bilateral Eyeballs", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Lens", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nasal Bone", "alias": "", "color": "0,159,255,25"},
                    {"name": "Frontal Process of Maxilla", "alias": "", "color": "255,95,0,25"},
                    {"name": "Bilateral Eyeballs", "alias": "", "color": "255,0,0,25"},
                    {"name": "Facial Contour", "alias": "", "color": "0,255,25,25"},
                    {"name": "Orbit", "alias": "", "color": "31,0,255,25"},
                    {"name": "Vitreous Humor", "alias": "", "color": "255,95,0,51"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Median Sagittal Plane of Face", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Frontal Bone", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nasal Bone", "alias": "", "color": "0,159,255,25"},
                    {"name": "Maxilla", "alias": "", "color": "255,95,0,25"},
                    {"name": "Mandible", "alias": "", "color": "255,0,0,25"},
                    {"name": "Tongue", "alias": "", "color": "0,255,25,25"},
                    {"name": "Nasal Septum", "alias": "", "color": "255,0,133,25"},
                    {"name": "Facial Contour", "alias": "", "color": "255,172,0,20"},
                    {"name": "Forehead", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nasal Tip", "alias": "", "color": "0,255,0,38"},
                    {"name": "Upper Lip", "alias": "", "color": "255,0,0,25"},
                    {"name": "Lower Lip", "alias": "", "color": "0,255,25,25"},
                    {"name": "Chin", "alias": "", "color": "255,0,133,51"},
                    {"name": "Mandible", "alias": "", "color": "0,170,255,51"},
                    {"name": "Oral Fissure", "alias": "", "color": "108,0,255,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Nose and Lip", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Nose", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nares", "alias": "", "color": "0,159,255,25"},
                    {"name": "Upper Lip", "alias": "", "color": "255,95,0,25"},
                    {"name": "Lower Vermilion", "alias": "", "color": "255,0,0,25"},
                    {"name": "Chin", "alias": "", "color": "0,255,25,25"},
                    {"name": "Nasal Tip", "alias": "", "color": "31,0,255,76"},
                    {"name": "Bilateral Alae Nasi", "alias": "", "color": "0,159,255,25"},
                    {"name": "Bilateral Nares", "alias": "", "color": "255,95,0,25"},
                    {"name": "Nasal Columella", "alias": "", "color": "255,0,0,25"},
                    {"name": "Upper Lip Skin", "alias": "", "color": "0,255,25,25"},
                    {"name": "Lower Lip Skin", "alias": "", "color": "255,0,133,51"},
                    {"name": "Upper Vermilion", "alias": "", "color": "255,172,0,25"},
                    {"name": "Philtrum", "alias": "", "color": "108,0,255,76"},
                    {"name": "Oral Fissure", "alias": "", "color": "0,255,6,25"},
                    {"name": "Lower Lip", "alias": "", "color": "255,0,0,25"},
                    {"name": "Mental Region", "alias": "", "color": "255,0,100,51"},
                    {"name": "Vermilion", "alias": "", "color": "255,172,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Sagittal Plane of External Auricle", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Auricle", "alias": "", "color": "31,0,255,25"},
                    {"name": "Helix", "alias": "", "color": "31,0,255,25"},
                    {"name": "Lobule", "alias": "", "color": "0,159,255,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Transverse Plane of Skull Vault", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Skull Halo", "alias": "", "color": "31,0,255,25"},
                    {"name": "Midline of Brain", "alias": "", "color": "0,159,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "255,95,0,25"},
                    {"name": "Parietooccipital Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Central Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Precentral Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Postcentral Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Superior Frontal Sulcus", "alias": "", "color": "255,255,0,102"},
                    {"name": "Body of Lateral Ventricle", "alias": "", "color": "2,255,73,25"},
                    {"name": "choroid plexus", "alias": "", "color": "255,0,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Transverse Plane of Cavum Septi Pellucidi", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "skull Halo", "alias": "", "color": "31,0,255,25"},
                    {"name": "Midline of Brain", "alias": "", "color": "0,159,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "255,95,0,25"},
                    {"name": "White Matter", "alias": "", "color": "255,0,0,25"},
                    {"name": "Parietooccipital Sulcus", "alias": "", "color": "0,255,25,25"},
                    {"name": "Splenium of Corpus Callosum", "alias": "", "color": "255,0,133,25"},
                    {"name": "Genu of Corpus Callosum", "alias": "", "color": "255,172,0,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "108,0,255,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "0,82,255,25"},
                    {"name": "Body of Lateral Ventricle", "alias": "", "color": "0,255,6,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,0,152,25"},
                    {"name": "choroid plexus", "alias": "", "color": "223,0,255,25"},
                    {"name": "Body of Fornix", "alias": "", "color": "12,0,255,25"},
                    {"name": "Vergae Cavity", "alias": "", "color": "0,255,178,25"},
                    {"name": "Central Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Precentral Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Postcentral Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Superior Frontal Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Inferior Frontal Sulcus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "255,0,0,25"},
                    {"name": "Insula", "alias": "", "color": "255,0,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Median Sagittal Plane of Cerebrum", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "31,0,255,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "0,159,255,25"},
                    {"name": "Vergae Cavity", "alias": "", "color": "255,95,0,25"},
                    {"name": "Cavum Veli Interpositi", "alias": "", "color": "255,0,0,25"},
                    {"name": "Third Ventricle", "alias": "", "color": "0,255,25,25"},
                    {"name": "Fourth Ventricle", "alias": "", "color": "255,0,133,25"},
                    {"name": "Vermis of Cerebellum", "alias": "", "color": "255,172,0,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "255,0,152,25"},
                    {"name": "Anterior Cerebral Artery", "alias": "", "color": "0,82,255,25"},
                    {"name": "Pericallosal Artery", "alias": "", "color": "0,255,6,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "255,0,152,25"},
                    {"name": "Brainstem", "alias": "", "color": "223,0,255,25"},
                    {"name": "Skull", "alias": "", "color": "12,0,255,25"},
                    {"name": "Falx Cerebri", "alias": "", "color": "0,255,178,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Paramedian Sagittal Plane of Cerebrum", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "31,0,255,25"},
                    {"name": "Caudothalamic Sulcus", "alias": "", "color": "0,159,255,25"},
                    {"name": "Caudate Nucleus", "alias": "", "color": "255,95,0,25"},
                    {"name": "thalamic", "alias": "", "color": "255,0,0,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "0,255,25,25"},
                    {"name": "Lateral Ventricle", "alias": "", "color": "255,0,133,25"},
                    {"name": "choroid plexus", "alias": "", "color": "255,172,0,25"},
                    {"name": "White Matter", "alias": "", "color": "108,0,255,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Sagittal Plane of Cerebral Hemisphere", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Cerebellum", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "cerebellar hemisphere", "alias": "", "color": "255,0,0,25"},
                    {"name": "Vermis of Cerebellum", "alias": "", "color": "0,255,25,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "255,0,133,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "255,172,0,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "108,0,255,25"},
                    {"name": "Insula", "alias": "", "color": "0,82,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "0,255,6,25"},
                    {"name": "thalamic", "alias": "", "color": "255,0,152,25"},
                    {"name": "Skull", "alias": "", "color": "223,0,255,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Atrium of Lateral Ventricle", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "Lateral Ventricle", "alias": "", "color": "255,0,0,25"},
                    {"name": "choroid plexus", "alias": "", "color": "0,255,25,25"},
                    {"name": "Midline of Brain", "alias": "", "color": "255,0,133,25"},
                    {"name": "Skull", "alias": "", "color": "255,172,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Occipital Lobe", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "White Matter", "alias": "", "color": "0,159,255,25"},
                    {"name": "Midline of Brain", "alias": "", "color": "255,95,0,25"},
                    {"name": "Skull", "alias": "", "color": "255,0,0,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane Through Frontal Lobe", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Midline of Brain", "alias": "", "color": "31,0,255,25"},
                    {"name": "Cerebral Cortex of Frontal Lobe", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "Eyeball", "alias": "", "color": "255,0,0,25"},
                    {"name": "Skull", "alias": "", "color": "0,255,25,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Anterior Horn of Lateral Ventricle", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,95,0,25"},
                    {"name": "Head of Caudate Nucleus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "0,255,25,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "255,0,133,25"},
                    {"name": "Insula", "alias": "", "color": "255,172,0,25"},
                    {"name": "Skull", "alias": "", "color": "108,0,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "0,82,255,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Coronal Plane of Body of Lateral Ventricle", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "Skull", "alias": "", "color": "255,0,0,25"},
                    {"name": "thalamic", "alias": "", "color": "0,255,25,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "255,0,133,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "255,172,0,25"},
                    {"name": "Brainstem", "alias": "", "color": "108,0,255,25"},
                    {"name": "Insula", "alias": "", "color": "0,82,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "0,255,6,25"},
                    {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
        {"name": "Fetal NT Plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Nuchal Translucency", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nasal Bone", "alias": "", "color": "0,159,255,25"},
                    {"name": "Nasal Tip and Nasal Skin", "alias": "", "color": "255,95,0,25"},
                    {"name": "Diencephalon", "alias": "", "color": "255,0,0,25"},
                    {"name": "cerebellar hemisphere", "alias": "", "color": "0,255,25,25"},
                    {"name": "Rhombencephalon", "alias": "", "color": "255,0,133,25"},
                    {"name": "Maxilla", "alias": "", "color": "74,232,82,25"},
                    {"name": "Dot-shaped Mandible", "alias": "", "color": "108,0,255,25"}]},
        {"name": "Fetal CRL Measurement Plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Nasal Tip and Nasal Skin", "alias": "", "color": "31,0,255,25"},
                    {"name": "Dot-shaped Mandible", "alias": "", "color": "0,159,255,25"},
                    {"name": "Maxilla", "alias": "", "color": "255,95,0,25"},
                    {"name": "Diencephalon", "alias": "", "color": "255,0,0,25"},
                    {"name": "Nasal Bone", "alias": "", "color": "0,255,25,25"},
                    {"name": "Genitalia", "alias": "", "color": "107,230,50,25"},
                    {"name": "Rhombencephalon", "alias": "", "color": "105,34,227,25"},
                    {"name": "Rib", "alias": "", "color": "250,126,184,25"},
                    {"name": "Clavicle", "alias": "", "color": "250,211,112,25"},
                    {"name": "Lateral Ventricle", "alias": "", "color": "103,113,194,25"},
                    {"name": "Strip-shaped Mandible", "alias": "", "color": "247,185,134,25"}]},
        {"name": "Median Sagittal Plane of Fetal Cerebrum", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Corpus Callosum", "alias": "", "color": "31,0,255,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "0,159,255,25"},
                    {"name": "Vergae Cavity", "alias": "", "color": "255,95,0,25"},
                    {"name": "Cavum Veli Interpositi", "alias": "", "color": "255,0,0,25"},
                    {"name": "Third Ventricle", "alias": "", "color": "0,255,25,25"},
                    {"name": "Fourth Ventricle", "alias": "", "color": "255,0,133,25"},
                    {"name": "Vermis of Cerebellum", "alias": "", "color": "255,172,0,25"},
                    {"name": "Posterior Fossa Cistern", "alias": "", "color": "255,0,152,25"},
                    {"name": "Anterior Cerebral Artery", "alias": "", "color": "0,82,255,25"},
                    {"name": "Pericallosal Artery", "alias": "", "color": "0,255,6,25"},
                    {"name": "Brainstem", "alias": "", "color": "223,0,255,25"},
                    {"name": "Skull", "alias": "", "color": "12,0,255,25"},
                    {"name": "Falx Cerebri", "alias": "", "color": "0,255,178,25"}]},
        {"name": "Paramedian Sagittal Plane", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "31,0,255,25"},
                    {"name": "Caudothalamic Sulcus", "alias": "", "color": "0,159,255,25"},
                    {"name": "Caudate Nucleus", "alias": "", "color": "255,95,0,25"},
                    {"name": "thalamic", "alias": "", "color": "255,0,0,25"},
                    {"name": "Cerebral Parenchyma", "alias": "", "color": "0,255,25,25"},
                    {"name": "Lateral Ventricle", "alias": "", "color": "255,0,133,25"},
                    {"name": "choroid plexus", "alias": "", "color": "255,172,0,25"},
                    {"name": "White Matter", "alias": "", "color": "108,0,255,25"}]},
        {"name": "Coronal Plane Through Anterior Horn", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,95,0,25"},
                    {"name": "Head of Caudate Nucleus", "alias": "", "color": "255,0,0,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "0,255,25,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "255,0,133,25"},
                    {"name": "Insula", "alias": "", "color": "255,172,0,25"},
                    {"name": "Skull", "alias": "", "color": "108,0,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "0,82,255,25"}]},
        {"name": "Coronal Plane Through Body of Lateral Ventricle", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Cerebral Parenchyma", "alias": "", "color": "31,0,255,25"},
                    {"name": "Sylvian Fissure", "alias": "", "color": "0,159,255,25"},
                    {"name": "White Matter", "alias": "", "color": "255,95,0,25"},
                    {"name": "Skull", "alias": "", "color": "255,0,0,25"},
                    {"name": "thalamic", "alias": "", "color": "0,255,25,25"},
                    {"name": "Corpus Callosum", "alias": "", "color": "255,0,133,25"},
                    {"name": "Cavum Septi Pellucidi", "alias": "", "color": "255,172,0,25"},
                    {"name": "Brainstem", "alias": "", "color": "108,0,255,25"},
                    {"name": "Insula", "alias": "", "color": "0,82,255,25"},
                    {"name": "Septum Pellucidum", "alias": "", "color": "0,255,6,25"}]},
        {"name": "Coronal Plane of Face", "showOtherInfo": 0, "subclass": [],
         "config": [{"name": "Frontal Bone", "alias": "", "color": "31,0,255,25"},
                    {"name": "Nasal Bone", "alias": "", "color": "0,159,255,25"},
                    {"name": "Maxilla", "alias": "", "color": "255,95,0,25"},
                    {"name": "Mandible", "alias": "", "color": "255,0,0,25"},
                    {"name": "Tongue", "alias": "", "color": "0,255,25,25"}]}
    ]},
        "Cardiothoracic": {"index": 1, "annotationParts": [
            {"name": "Four-Chamber View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricle", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "0,255,25,25"},
                        {"name": "Right Lung", "alias": "", "color": "255,0,133,25"},
                        {"name": "Closed Mitral Valve", "alias": "", "color": "255,172,0,25"},
                        {"name": "Open Mitral Valve", "alias": "", "color": "108,0,255,25"},
                        {"name": "Closed Tricuspid Valve", "alias": "", "color": "0,82,255,25"},
                        {"name": "Open Tricuspid Valve", "alias": "", "color": "0,255,6,25"},
                        {"name": "Pulmonary Venous Angle", "alias": "", "color": "255,0,152,25"},
                        {"name": "Spine", "alias": "", "color": "223,0,255,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "12,0,255,25"},
                        {"name": "Rib", "alias": "", "color": "0,255,178,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "108,255,0,25"},
                        {"name": "Foramen Ovale Valve", "alias": "", "color": "184,0,255,25"},
                        {"name": "Cardiac Area", "alias": "", "color": "255,0,76,25"},
                        {"name": "Thoracic Area", "alias": "", "color": "146,255,0,25"},
                        {"name": "Azygos Vein", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "7,31,255,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Umbilical Vein", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,255,127,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Parasternal Four-Chamber View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricle", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "0,255,25,25"},
                        {"name": "Right Lung", "alias": "", "color": "255,0,133,25"},
                        {"name": "Closed Mitral Valve", "alias": "", "color": "255,172,0,25"},
                        {"name": "Open Mitral Valve", "alias": "", "color": "108,0,255,25"},
                        {"name": "Closed Tricuspid Valve", "alias": "", "color": "0,82,255,25"},
                        {"name": "Open Tricuspid Valve", "alias": "", "color": "0,255,6,25"},
                        {"name": "Pulmonary Venous Angle", "alias": "", "color": "255,0,152,25"},
                        {"name": "Spine", "alias": "", "color": "223,0,255,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "12,0,255,25"},
                        {"name": "Rib", "alias": "", "color": "0,255,178,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "108,255,0,25"},
                        {"name": "Foramen Ovale Valve", "alias": "", "color": "184,0,255,25"},
                        {"name": "Cardiac Area", "alias": "", "color": "255,0,76,25"},
                        {"name": "Thoracic Area", "alias": "", "color": "146,255,0,25"},
                        {"name": "Azygos Vein", "alias": "", "color": "255,0,127,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "170,0,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "170,255,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Base Four-Chamber View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricle", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "0,255,25,25"},
                        {"name": "Right Lung", "alias": "", "color": "255,0,133,25"},
                        {"name": "Closed Mitral Valve", "alias": "", "color": "255,172,0,25"},
                        {"name": "Open Mitral Valve", "alias": "", "color": "108,0,255,25"},
                        {"name": "Closed Tricuspid Valve", "alias": "", "color": "0,82,255,25"},
                        {"name": "Open Tricuspid Valve", "alias": "", "color": "0,255,6,25"},
                        {"name": "Pulmonary Venous Angle", "alias": "", "color": "255,0,152,25"},
                        {"name": "Spine", "alias": "", "color": "223,0,255,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "12,0,255,25"},
                        {"name": "Rib", "alias": "", "color": "0,255,178,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "108,255,0,25"},
                        {"name": "Foramen Ovale Valve", "alias": "", "color": "184,0,255,25"},
                        {"name": "Cardiac Area", "alias": "", "color": "255,0,76,25"},
                        {"name": "Thoracic Area", "alias": "", "color": "146,255,0,25"},
                        {"name": "Azygos Vein", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,165,38,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Umbilical Vein", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "255,0,0,25"},
                        {"name": "Trachea", "alias": "", "color": "85,170,255,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Apical Five-Chamber View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricle and Outflow Tract", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "255,0,0,25"},
                        {"name": "Mitral Valve", "alias": "", "color": "0,255,25,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "0,82,255,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "0,82,255,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,133,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Outflow Tract", "alias": "", "color": "255,95,0,25"},
                        {"name": "Closed Mitral Valve", "alias": "", "color": "0,82,255,25"},
                        {"name": "Rib", "alias": "", "color": "108,0,255,25"},
                        {"name": "Tricuspid Valve", "alias": "", "color": "255,0,0,128"},
                        {"name": "Aortic Valve", "alias": "", "color": "170,85,255,128"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Left Ventricular Outflow Tract View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricle and Outflow Tract", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "255,0,0,25"},
                        {"name": "Mitral Valve", "alias": "", "color": "0,255,25,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "108,0,255,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "223,0,255,25"},
                        {"name": "Aorta and Aortic Valve", "alias": "", "color": "12,0,255,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,133,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Outflow Tract", "alias": "", "color": "255,95,0,128"},
                        {"name": "Left Lung", "alias": "", "color": "255,255,0,25"},
                        {"name": "Right Lung", "alias": "", "color": "170,255,255,25"},
                        {"name": "Left Ventricle", "alias": "", "color": "85,85,255,128"},
                        {"name": "Aortic Valve", "alias": "", "color": "249,254,255,128"},
                        {"name": "Rib", "alias": "", "color": "108,0,255,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Right Ventricular Outflow Tract View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Right Ventricle and Outflow Tract", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Pulmonary Artery", "alias": "", "color": "255,95,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "0,255,25,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Ventricle", "alias": "", "color": "0,255,6,25"},
                        {"name": "Pulmonary Valve", "alias": "", "color": "223,0,255,25"},
                        {"name": "Right Superior Vena Cava", "alias": "", "color": "12,0,255,25"},
                        {"name": "Trachea", "alias": "", "color": "0,255,178,25"},
                        {"name": "Superior Vena Cava", "alias": "", "color": "108,255,0,25"},
                        {"name": "Aortic Arch", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Ventricular Cavity", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Cavity", "alias": "", "color": "255,0,0,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Main Pulmonary Artery and Ductus Arteriosus", "alias": "", "color": "255,0,0,25"},
                        {"name": "Spine", "alias": "", "color": "0,255,6,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "31,0,255,25"},
                        {"name": "Main Pulmonary Artery with Ductus Arteriosus", "alias": "", "color": "0,159,255,128"},
                        {"name": "Ductus Arteriosus", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "255,255,0,25"},
                        {"name": "Right Lung", "alias": "", "color": "170,255,255,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "255,0,152,25"},
                        {"name": "Right Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Closed Tricuspid Valve", "alias": "", "color": "255,95,0,25"},
                        {"name": "Open Tricuspid Valve", "alias": "", "color": "255,0,0,25"},
                        {"name": "Main Pulmonary Artery", "alias": "", "color": "0,255,25,25"},
                        {"name": "Rib", "alias": "", "color": "0,82,255,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "0,255,178,25"},
                        {"name": "Left Pulmonary Artery", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Short-Axis View of Cardiac Base", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Ventricle and Outflow Tract", "alias": "", "color": "0,159,255,25"},
                        {"name": "Main Pulmonary Artery and Ductus Arteriosus", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Pulmonary Artery", "alias": "", "color": "255,0,152,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "255,0,133,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "108,0,255,25"},
                        {"name": "Left Lung", "alias": "", "color": "0,82,255,25"},
                        {"name": "Right Lung", "alias": "", "color": "0,255,6,25"},
                        {"name": "Right Pulmonary Artery", "alias": "", "color": "255,0,152,25"},
                        {"name": "Pulmonary Valve", "alias": "", "color": "223,0,255,25"},
                        {"name": "Spine", "alias": "", "color": "0,255,6,25"},
                        {"name": "Right Ventricular Wall", "alias": "", "color": "255,0,0,25"},
                        {"name": "Atrial Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Ventricular Septum", "alias": "", "color": "255,0,0,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "0,159,255,25"},
                        {"name": "Main Pulmonary Artery with Ductus Arteriosus", "alias": "", "color": "255,95,0,25"},
                        {"name": "Ductus Arteriosus", "alias": "", "color": "255,172,0,25"},
                        {"name": "Right Ventricle", "alias": "", "color": "0,159,255,25"},
                        {"name": "Closed Tricuspid Valve", "alias": "", "color": "255,95,0,25"},
                        {"name": "Open Tricuspid Valve", "alias": "", "color": "255,0,0,25"},
                        {"name": "Main Pulmonary Artery", "alias": "", "color": "0,255,25,25"},
                        {"name": "Rib", "alias": "", "color": "0,82,255,25"},
                        {"name": "Aortic Arch", "alias": "", "color": "223,0,255,25"},
                        {"name": "Right Superior Vena Cava", "alias": "", "color": "0,82,255,25"},
                        {"name": "Trachea", "alias": "", "color": "85,255,255,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Three-Vessel View", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Main Pulmonary Artery", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Pulmonary Artery", "alias": "", "color": "0,159,255,25"},
                        {"name": "Ductus Arteriosus", "alias": "", "color": "255,95,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "255,0,0,25"},
                        {"name": "Rib", "alias": "", "color": "0,255,25,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"},
                        {"name": "Superior Vena Cava", "alias": "", "color": "108,0,255,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,133,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Three-Vessel Trachea View", "showOtherInfo": 1, "subclass": ["Apical 3VT View", "Parasternal 3VT View", "Base 3VT View"],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Main Pulmonary Artery with Ductus Arteriosus", "alias": "", "color": "31,0,255,25"},
                        {"name": "Aortic Arch", "alias": "", "color": "0,159,255,25"},
                        {"name": "Trachea", "alias": "", "color": "255,95,0,25"},
                        {"name": "Superior Vena Cava", "alias": "", "color": "255,0,0,25"},
                        {"name": "Thymus", "alias": "", "color": "0,255,25,25"},
                        {"name": "Sternum", "alias": "", "color": "255,172,0,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "108,0,255,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,133,25"},
                        {"name": "Main Pulmonary Artery and Ductus Arteriosus", "alias": "", "color": "31,0,255,25"},
                        {"name": "Pulmonary Artery and Ductus Arteriosus", "alias": "", "color": "200,100,200,128"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Left Thoracic Sagittal View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Heart", "alias": "", "color": "255,95,0,25"},
                        {"name": "Diaphragm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Stomach", "alias": "", "color": "0,255,25,25"},
                        {"name": "Liver", "alias": "", "color": "255,0,133,25"},
                        {"name": "Right Kidney", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Kidney", "alias": "", "color": "108,0,255,25"},
                        {"name": "Left Lung", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Lung", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Adrenal Gland", "alias": "", "color": "85,85,255,25"},
                        {"name": "Left Renal Pelvis", "alias": "", "color": "85,85,255,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Right Thoracic Sagittal View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Heart", "alias": "", "color": "255,95,0,25"},
                        {"name": "Diaphragm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Stomach", "alias": "", "color": "0,255,25,25"},
                        {"name": "Liver", "alias": "", "color": "255,0,133,25"},
                        {"name": "Right Kidney", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Kidney", "alias": "", "color": "108,0,255,25"},
                        {"name": "Gallbladder", "alias": "", "color": "255,0,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Lung", "alias": "", "color": "0,159,255,25"},
                        {"name": "Right Adrenal Gland", "alias": "", "color": "0,255,6,25"},
                        {"name": "Right Renal Pelvis", "alias": "", "color": "255,0,152,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Thoracic Coronal View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Heart", "alias": "", "color": "255,95,0,25"},
                        {"name": "Diaphragm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Stomach", "alias": "", "color": "0,255,25,25"},
                        {"name": "Liver", "alias": "", "color": "255,0,133,25"},
                        {"name": "Gallbladder", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Lung", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Lung", "alias": "", "color": "0,159,255,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Apical Five-Chamber", "showOtherInfo": 1, "subclass": [],
             "config": [{"name": "Left Atrium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Right Atrium", "alias": "", "color": "0,159,255,25"},
                        {"name": "Left Ventricular Outflow Tract", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Ventricular Outflow Tract", "alias": "", "color": "255,0,0,25"},
                        {"name": "Mitral Valve", "alias": "", "color": "0,255,25,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "108,0,255,25"},
                        {"name": "Closed Mitral Valve", "alias": "", "color": "0,82,255,25"}]},
            {"name": "Left Diaphragm Sagittal View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Heart", "alias": "", "color": "255,95,0,25"},
                        {"name": "Diaphragm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Stomach", "alias": "", "color": "0,255,25,25"},
                        {"name": "Liver", "alias": "", "color": "255,0,133,25"},
                        {"name": "Right Kidney", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Kidney", "alias": "", "color": "108,0,255,25"}]},
            {"name": "Right Diaphragm Sagittal View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Heart", "alias": "", "color": "255,95,0,25"},
                        {"name": "Diaphragm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Stomach", "alias": "", "color": "0,255,25,25"},
                        {"name": "Liver", "alias": "", "color": "255,0,133,25"},
                        {"name": "Right Kidney", "alias": "", "color": "255,172,0,25"},
                        {"name": "Left Kidney", "alias": "", "color": "108,0,255,25"},
                        {"name": "Gallbladder", "alias": "", "color": "255,0,0,25"}]},
            {"name": "Bifurcation View of Left and Right Pulmonary Arteries", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Main Pulmonary Artery", "alias": "", "color": "255,95,0,25"},
                        {"name": "Right Pulmonary Artery", "alias": "", "color": "255,95,0,25"},
                        {"name": "Left Pulmonary Artery", "alias": "", "color": "255,0,0,25"},
                        {"name": "Ascending Aorta", "alias": "", "color": "0,255,25,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,133,25"},
                        {"name": "Descending Aorta", "alias": "", "color": "255,172,0,25"}]}
        ]},

        "Limb and Skeleton": {"index": 3, "annotationParts": [
            {"name": "Sagittal View of Thoracolumbar Spine", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "", "alias": "", "color": "255,0,255,25"},
                        {"name": "Vertebral Body", "alias": "", "color": "255,0,0,48"},
                        {"name": "Vertebral Arch", "alias": "", "color": "255,0,0,25"},
                        {"name": "Skin Contour Line", "alias": "", "color": "255,0,0,25"},
                        {"name": "Spinal Cord", "alias": "", "color": "255,0,0,25"},
                        {"name": "Kidney", "alias": "", "color": "255,0,0,25"},
                        {"name": "Conus Medullaris", "alias": "", "color": "255,0,0,25"},
                        {"name": "Central Canal", "alias": "", "color": "255,0,0,25"},
                        {"name": "Cauda Equina", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subdural Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subarachnoid Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Sagittal View of Mid Spine", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Ossification Center of Vertebral Arch", "alias": "", "color": "255,0,255,48"},
                        {"name": "Ossification Center of Vertebral Body", "alias": "", "color": "0,255,255,48"},
                        {"name": "Vertebral Arch", "alias": "", "color": "255,0,0,25"},
                        {"name": "Skin Contour Line", "alias": "", "color": "255,255,0,25"},
                        {"name": "Spinal Cord", "alias": "", "color": "255,0,0,25"},
                        {"name": "Kidney", "alias": "", "color": "255,0,0,25"},
                        {"name": "Conus Medullaris", "alias": "", "color": "255,0,0,25"},
                        {"name": "Central Canal", "alias": "", "color": "255,0,0,25"},
                        {"name": "Cauda Equina", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subdural Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subarachnoid Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Sagittal View of Full Spine", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Ossification Center of Vertebral Body", "alias": "", "color": "255,0,255,25"},
                        {"name": "Ossification Center of Vertebral Arch", "alias": "", "color": "255,0,0,48"},
                        {"name": "Distal End of Spine", "alias": "", "color": "255,0,0,25"},
                        {"name": "Skull Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Spinal Cord", "alias": "", "color": "255,0,0,25"},
                        {"name": "Skin Contour Line", "alias": "", "color": "255,0,0,25"},
                        {"name": "Conus Medullaris", "alias": "", "color": "255,0,0,25"},
                        {"name": "Central Canal", "alias": "", "color": "255,0,0,25"},
                        {"name": "Cauda Equina", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subdural Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "Subarachnoid Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},

            {"name": "Sagittal View of Cervicothoracic Spine", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Ossification Center of Vertebral Body", "alias": "", "color": "255,0,255,25"},
                        {"name": "Ossification Center of Vertebral Arch", "alias": "", "color": "31,0,255,25"},
                        {"name": "Skull Contour", "alias": "", "color": "0,159,255,25"},
                        {"name": "Spinal Cord", "alias": "", "color": "255,95,0,25"},
                        {"name": "Skin Contour Line", "alias": "", "color": "255,0,0,25"},
                        {"name": "Conus Medullaris", "alias": "", "color": "255,0,0,25"},
                        {"name": "Kidney", "alias": "", "color": "0,255,25,25"},
                        {"name": "Lung", "alias": "", "color": "255,0,133,25"},
                        {"name": "Cauda Equina", "alias": "", "color": "255,172,0,25"},
                        {"name": "Central Canal", "alias": "", "color": "108,0,255,25"},
                        {"name": "Rib", "alias": "", "color": "0,82,255,25"},
                        {"name": "Subarachnoid Space", "alias": "", "color": "255,0,0,51"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Sagittal View of Lumbosacrococcygeal Spine", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Ossification Center of Vertebral Body", "alias": "", "color": "255,0,255,25"},
                        {"name": "Ossification Center of Vertebral Arch", "alias": "", "color": "31,0,255,25"},
                        {"name": "Distal End of Spine", "alias": "", "color": "0,159,255,25"},
                        {"name": "Spinal Cord and Conus Medullaris", "alias": "", "color": "255,95,0,25"},
                        {"name": "Skin Contour Line", "alias": "", "color": "255,0,0,25"},
                        {"name": "Sacrococcygeal Skin Line", "alias": "", "color": "0,255,25,25"},
                        {"name": "Vertebral Arch", "alias": "", "color": "0,159,255,51"},
                        {"name": "Spinal Cord", "alias": "", "color": "255,95,0,25"},
                        {"name": "Kidney", "alias": "", "color": "0,255,25,25"},
                        {"name": "Lung", "alias": "", "color": "255,0,133,25"},
                        {"name": "Central Canal", "alias": "", "color": "108,0,255,25"},
                        {"name": "Rib", "alias": "", "color": "0,82,255,25"},
                        {"name": "Subarachnoid Space", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Transverse View at Scapula Level", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Scapula", "alias": "", "color": "31,0,255,25"},
                        {"name": "Spine", "alias": "", "color": "0,159,255,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Long Axis View of Left Humerus", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Humerus", "alias": "", "color": "31,0,255,25"},
                        {"name": "Proximal Epiphysis of Humerus", "alias": "", "color": "0,159,255,25"},
                        {"name": "Distal Epiphysis of Humerus", "alias": "", "color": "255,95,0,25"},
                        {"name": "Whole Upper Arm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Forearm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Hand Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Upper Arm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Coronal View of Left Palm", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Palm Contour", "alias": "", "color": "31,0,255,25"},
                        {"name": "Ulna", "alias": "", "color": "0,159,255,25"},
                        {"name": "Radius", "alias": "", "color": "255,95,0,25"},
                        {"name": "1st Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "2nd Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "3rd Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "4th Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "5th Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "1st Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "2nd Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "3rd Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "4th Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "5th Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "Metacarpal Bone", "alias": "", "color": "31,0,255,25"},
                        {"name": "Tension State", "alias": "", "color": "255,0,0,25"},
                        {"name": "Fist State", "alias": "", "color": "255,0,0,25"},
                        {"name": "Forearm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Transverse View of Palm", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "1st Digit", "alias": "", "color": "31,0,255,25"},
                        {"name": "2nd Digit", "alias": "", "color": "0,159,255,25"},
                        {"name": "3rd Digit", "alias": "", "color": "255,95,0,25"},
                        {"name": "4th Digit", "alias": "", "color": "255,0,0,25"},
                        {"name": "5th Digit", "alias": "", "color": "0,255,25,25"},
                        {"name": "Metacarpal Bone", "alias": "", "color": "31,0,255,25"},
                        {"name": "Palm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Open Hand State", "alias": "", "color": "255,0,0,25"},
                        {"name": "Fist State", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Transverse View at Ilium Level", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Ilium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Bladder", "alias": "", "color": "0,159,255,25"},
                        {"name": "Spine", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Long Axis View of Left Femur", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Femur", "alias": "", "color": "31,0,255,25"},
                        {"name": "Metaphysis", "alias": "", "color": "0,159,255,51"},
                        {"name": "PEF", "alias": "", "color": "0,159,255,25"},
                        {"name": "Distal Epiphysis of Femur", "alias": "", "color": "255,95,0,25"},
                        {"name": "Thigh Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Calf Contour", "alias": "", "color": "0,255,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Coronal View of Left Tibia and Fibula", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Tibia", "alias": "", "color": "31,0,255,25"},
                        {"name": "Fibula", "alias": "", "color": "0,159,255,25"},
                        {"name": "Distal Epiphysis of Tibia", "alias": "", "color": "255,95,0,25"},
                        {"name": "Proximal Epiphysis of Fibula", "alias": "", "color": "255,0,0,25"},
                        {"name": "Distal Epiphysis of Fibula", "alias": "", "color": "0,255,25,25"},
                        {"name": "Proximal Epiphysis of Tibia", "alias": "", "color": "255,0,133,25"},
                        {"name": "Calf Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Thigh Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Foot Contour", "alias": "", "color": "67,170,11,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Left Foot Plantar View", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Foot Contour", "alias": "", "color": "31,0,255,25"},
                        {"name": "1st Toe", "alias": "", "color": "0,159,255,25"},
                        {"name": "2nd Toe", "alias": "", "color": "255,95,0,25"},
                        {"name": "3rd Toe", "alias": "", "color": "255,0,0,25"},
                        {"name": "4th Toe", "alias": "", "color": "0,255,25,25"},
                        {"name": "5th Toe", "alias": "", "color": "255,0,133,25"},
                        {"name": "Metatarsal Bone", "alias": "", "color": "0,170,0,76"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Sagittal View of Leg", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Knee Joint", "alias": "", "color": "31,0,255,25"},
                        {"name": "Calf with Foot", "alias": "", "color": "0,159,255,25"},
                        {"name": "Thigh Section", "alias": "", "color": "255,95,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Coronal View of Left Ulna and Radius", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                        {"name": "Ulna", "alias": "", "color": "31,0,255,25"},
                        {"name": "Radius", "alias": "", "color": "0,159,255,25"},
                        {"name": "Distal Epiphysis of Ulna", "alias": "", "color": "255,95,0,25"},
                        {"name": "Proximal Epiphysis of Radius", "alias": "", "color": "255,0,0,25"},
                        {"name": "Distal Epiphysis of Radius", "alias": "", "color": "0,255,25,25"},
                        {"name": "Proximal Epiphysis of Ulna", "alias": "", "color": "255,0,133,25"},
                        {"name": "Forearm Contour", "alias": "", "color": "255,0,128,25"},
                        {"name": "Upper Arm Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "Hand Contour", "alias": "", "color": "255,0,0,25"},
                        {"name": "ROI", "alias": "", "color": "255,0,0,64"},
                        {"name": "Palm", "alias": "", "color": "255,0,0,25"},
                        {"name": "Metacarpal Bone", "alias": "", "color": "255,0,0,25"},
                        {"name": "Phalanx", "alias": "", "color": "255,0,0,25"}]},
            {"name": "Transverse View of Fetal Scapula", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Scapula", "alias": "", "color": "31,0,255,25"},
                        {"name": "Spine", "alias": "", "color": "0,159,255,25"}]},
            {"name": "Transverse View of Fetal Bilateral Iliac Bones", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Ilium", "alias": "", "color": "31,0,255,25"},
                        {"name": "Bladder", "alias": "", "color": "0,159,255,25"}]},
            {"name": "Sagittal View of Left Calf", "showOtherInfo": 0, "subclass": [],
             "config": [{"name": "Knee Joint", "alias": "", "color": "31,0,255,25"},
                        {"name": "Calf with Foot", "alias": "", "color": "0,159,255,25"},
                        {"name": "Thigh Section", "alias": "", "color": "255,95,0,25"}]}
        ]},

        "BodyPart": {"index": 5, "annotationParts": [
            {"name": "Combined Spine", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Abdomen", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Liver", "alias": "", "color": "31,0,255,25"},
                                {"name": "Spine", "alias": "", "color": "0,159,255,25"},
                                {"name": "Umbilical Vein and Portal Vein", "alias": "", "color": "255,95,0,25"},
                                {"name": "Stomach", "alias": "", "color": "255,0,0,25"},
                                {"name": "Spleen", "alias": "", "color": "0,255,25,25"},
                                {"name": "Adrenal Gland", "alias": "", "color": "255,0,133,25"},
                                {"name": "Inferior Vena Cava", "alias": "", "color": "255,172,0,25"},
                                {"name": "Descending Aorta", "alias": "", "color": "108,0,255,25"},
                                {"name": "Rib", "alias": "", "color": "0,82,255,25"},
                                {"name": "Abdominal Wall", "alias": "", "color": "255,85,127,128"},
                                {"name": "Kidney", "alias": "", "color": "215,194,255,128"},
                                {"name": "Lung", "alias": "", "color": "96,170,0,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Femur", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Femur", "alias": "", "color": "31,0,255,25"},
                                {"name": "Metaphysis", "alias": "", "color": "0,159,255,25"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Humerus", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Humerus", "alias": "", "color": "200,100,200,128"},
                                {"name": "Metaphysis", "alias": "", "color": "255,0,0,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "thalamic", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "skull Halo", "alias": "S", "color": "31,0,255,76"},
                                {"name": "Falx Cerebri", "alias": "BM", "color": "0,159,255,25"},
                                {"name": "Cerebral Parenchyma", "alias": "", "color": "255,95,0,25"},
                                {"name": "thalamic", "alias": "T", "color": "255,0,0,25"},
                                {"name": "Third Ventricle", "alias": "TV", "color": "0,255,25,25"},
                                {"name": "posterior horn of the lateral ventricle", "alias": "", "color": "255,0,133,25"},
                                {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,172,0,25"},
                                {"name": "choroid plexus", "alias": "CP", "color": "108,0,255,25"},
                                {"name": "Sylvian Fissure", "alias": "LS", "color": "0,82,255,25"},
                                {"name": "Cavum Septi Pellucidi", "alias": "CSP", "color": "0,255,6,25"},
                                {"name": "Septum Pellucidum", "alias": "", "color": "255,0,152,25"},
                                {"name": "Superior Temporal Sulcus", "alias": "", "color": "223,0,255,25"},
                                {"name": "Inferior Temporal Sulcus", "alias": "", "color": "12,0,255,25"},
                                {"name": "Cingulate Sulcus", "alias": "", "color": "0,255,178,25"},
                                {"name": "Column of Fornix", "alias": "", "color": "108,255,0,25"},
                                {"name": "Superior Frontal Sulcus", "alias": "", "color": "184,0,255,25"},
                                {"name": "Parietooccipital Sulcus", "alias": "", "color": "255,0,76,25"},
                                {"name": "Calcarine Sulcus", "alias": "", "color": "146,255,0,25"},
                                {"name": "Corpus Callosum", "alias": "", "color": "51,0,255,25"},
                                {"name": "Insula", "alias": "", "color": "0,197,255,25"},
                                {"name": "Inferior Frontal Sulcus", "alias": "", "color": "255,203,219,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Lateral Ventricle", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "skull Halo", "alias": "", "color": "31,0,255,25"},
                                {"name": "Falx Cerebri", "alias": "", "color": "0,159,255,25"},
                                {"name": "Cerebral Parenchyma", "alias": "", "color": "255,95,0,25"},
                                {"name": "thalamic", "alias": "", "color": "255,0,0,25"},
                                {"name": "Third Ventricle", "alias": "", "color": "0,255,25,25"},
                                {"name": "posterior horn of the lateral ventricle", "alias": "", "color": "255,0,133,25"},
                                {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "255,172,0,25"},
                                {"name": "choroid plexus", "alias": "", "color": "108,0,255,25"},
                                {"name": "Sylvian Fissure", "alias": "", "color": "0,82,255,25"},
                                {"name": "Cavum Septi Pellucidi", "alias": "", "color": "0,255,6,25"},
                                {"name": "Septum Pellucidum", "alias": "", "color": "255,0,152,25"},
                                {"name": "Superior Temporal Sulcus", "alias": "", "color": "223,0,255,25"},
                                {"name": "Inferior Temporal Sulcus", "alias": "", "color": "12,0,255,25"},
                                {"name": "Cingulate Sulcus", "alias": "", "color": "0,255,178,25"},
                                {"name": "Column of Fornix", "alias": "", "color": "108,255,0,25"},
                                {"name": "Superior Frontal Sulcus", "alias": "", "color": "184,0,255,25"},
                                {"name": "Parietooccipital Sulcus", "alias": "", "color": "255,0,76,25"},
                                {"name": "Calcarine Sulcus", "alias": "", "color": "146,255,0,25"},
                                {"name": "Corpus Callosum", "alias": "", "color": "51,0,255,25"},
                                {"name": "Insula", "alias": "", "color": "0,197,255,25"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Cerebellum", "showOtherInfo": 0, "subclass": [],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "skull Halo", "alias": "", "color": "31,0,255,25"},
                                {"name": "Falx Cerebri", "alias": "", "color": "0,159,255,25"},
                                {"name": "cerebellar hemisphere", "alias": "", "color": "255,95,0,25"},
                                {"name": "Vermis of Cerebellum", "alias": "", "color": "255,0,0,25"},
                                {"name": "Fourth Ventricle", "alias": "", "color": "0,255,25,25"},
                                {"name": "Cerebral Parenchyma", "alias": "", "color": "255,0,133,25"},
                                {"name": "Midbrain", "alias": "", "color": "255,170,127,51"},
                                {"name": "thalamic", "alias": "", "color": "108,0,255,25"},
                                {"name": "Third Ventricle", "alias": "", "color": "0,82,255,25"},
                                {"name": "Anterior Horn of Lateral Ventricle", "alias": "", "color": "0,255,6,25"},
                                {"name": "Sylvian Fissure", "alias": "", "color": "255,0,152,25"},
                                {"name": "Cavum Septi Pellucidi", "alias": "", "color": "223,0,255,25"},
                                {"name": "Septum Pellucidum", "alias": "", "color": "12,0,255,25"},
                                {"name": "Superior Temporal Sulcus", "alias": "", "color": "0,255,178,25"},
                                {"name": "Inferior Temporal Sulcus", "alias": "", "color": "108,255,0,25"},
                                {"name": "Cingulate Sulcus", "alias": "", "color": "184,0,255,25"},
                                {"name": "Column of Fornix", "alias": "", "color": "255,0,76,25"},
                                {"name": "Corpus Callosum", "alias": "", "color": "146,255,0,25"},
                                {"name": "Insula", "alias": "", "color": "51,0,255,25"},
                                {"name": "Hippocampus", "alias": "", "color": "255,255,127,102"},
                                {"name": "Tentorium Cerebelli", "alias": "", "color": "170,0,0,102"},
                                {"name": "Superior Frontal Sulcus", "alias": "", "color": "0,0,0,128"},
                                {"name": "Inferior Frontal Sulcus", "alias": "", "color": "85,170,127,128"},
                                {"name": "Cerebral Aqueduct", "alias": "", "color": "255,255,0,255"},
                                {"name": "Posterior Fossa Cistern", "alias": "", "color": "0,170,255,51"},
                                {"name": "Cerebellomedullary Cistern", "alias": "", "color": "0,0,255,255"},
                                {"name": "Cerebral Peduncle", "alias": "", "color": "255,172,0,25"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Four-Chamber Heart", "showOtherInfo": 0, "subclass": ["Apical Four-Chamber", "Base Four-Chamber", "Parasternal Four-Chamber"],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Left Atrium", "alias": "", "color": "200,100,200,128"},
                                {"name": "Right Atrium", "alias": "", "color": "255,0,0,128"},
                                {"name": "Left Ventricle", "alias": "", "color": "255,128,0,128"},
                                {"name": "Right Ventricle", "alias": "", "color": "255,255,0,128"},
                                {"name": "Pulmonary Vein", "alias": "", "color": "0,255,0,128"},
                                {"name": "Descending Aorta", "alias": "", "color": "0,0,255,128"},
                                {"name": "Mitral Valve", "alias": "", "color": "0,255,255,128"},
                                {"name": "Tricuspid Valve", "alias": "", "color": "255,0,255,128"},
                                {"name": "Spine", "alias": "", "color": "200,100,200,128"},
                                {"name": "Sternum", "alias": "", "color": "255,0,0,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Left Ventricular Outflow Tract", "showOtherInfo": 0, "subclass": ["Apical Five-Chamber", "Base Five-Chamber", "Apical LVOT", "Parasternal LVOT"],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Left Ventricle", "alias": "", "color": "200,100,200,128"},
                                {"name": "Aorta", "alias": "", "color": "255,0,0,128"},
                                {"name": "Aortic Valve", "alias": "", "color": "255,128,0,128"},
                                {"name": "Right Ventricle", "alias": "", "color": "255,255,0,128"},
                                {"name": "Left Atrium", "alias": "", "color": "0,255,0,128"},
                                {"name": "Right Atrium", "alias": "", "color": "0,0,255,128"},
                                {"name": "Right Pulmonary Artery", "alias": "", "color": "0,255,255,128"},
                                {"name": "Descending Aorta", "alias": "", "color": "255,0,255,128"},
                                {"name": "Spine", "alias": "", "color": "200,100,200,128"},
                                {"name": "Sternum", "alias": "", "color": "255,0,0,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]},
            {"name": "Right Ventricular Outflow Tract", "showOtherInfo": 0, "subclass": ["Apical RVOT", "Base RVOT", "Parasternal RVOT", "Short-Axis View of Base"],
                     "config": [{"name": "Section Frame", "alias": "", "color": "255,0,255,25"},
                                {"name": "Right Ventricle", "alias": "", "color": "200,100,200,128"},
                                {"name": "Pulmonary Artery", "alias": "", "color": "255,0,0,128"},
                                {"name": "Pulmonary Valve", "alias": "", "color": "255,128,0,128"},
                                {"name": "Left Ventricle", "alias": "", "color": "255,255,0,128"},
                                {"name": "Right Atrium", "alias": "", "color": "0,255,0,128"},
                                {"name": "Left Atrium", "alias": "", "color": "0,0,255,128"},
                                {"name": "Ascending Aorta", "alias": "", "color": "0,255,255,128"},
                                {"name": "Aortic Arch", "alias": "", "color": "255,0,255,128"},
                                {"name": "Descending Aorta", "alias": "", "color": "200,100,200,128"},
                                {"name": "Left Pulmonary Artery", "alias": "", "color": "255,0,0,128"},
                                {"name": "Right Pulmonary Artery", "alias": "", "color": "255,128,0,128"},
                                {"name": "Ductus Arteriosus", "alias": "", "color": "255,255,0,128"},
                                {"name": "Spine", "alias": "", "color": "0,255,0,128"},
                                {"name": "Sternum", "alias": "", "color": "0,0,255,128"},
                                {"name": "ROI", "alias": "", "color": "255,0,0,64"}]}
        ]},
        },
    "standard": ["standard", "basic standard", "nonstandard"],
    "info": ["Other Period", "End Systole", "End Diastole"]
}


class ColorManager:
    def __init__(self):
        '''constructor'''
        self.color_mapping = {}

        body_parts = ANNOTATION_CONFIG['bodyPart']
        for part_config in body_parts.values():
            part_config = part_config['annotationParts']

            for configs in part_config:
                plane_type = configs['name']
                self.color_mapping[plane_type] = self.parse_color_mapping(configs['config'])

    @classmethod
    def parse_color_mapping(cls, configs):
        color_mapping = {}
        for config in configs:
            structure_name = config['name']
            alias = config['alias'] if 'alias' in config else ''
            color = config['color'].split(',')
            color = [int(x) for x in color]

            color_mapping[structure_name] = {
                'color': color,
                'alias': alias
            }
        return color_mapping

    def get_color(self, plane_name, structure_name):
        if plane_name in self.color_mapping:
            color_mapping = self.color_mapping[plane_name]

            if structure_name in color_mapping:
                return color_mapping[structure_name]['color']

        return [255, 255, 0, 255]

    def get_alias(self, plane_name, structure_name):
        if plane_name in self.color_mapping:
            color_mapping = self.color_mapping[plane_name]

            if structure_name in color_mapping:
                return color_mapping[structure_name]['alias']

        return ''