_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
#  WEIGHTS: "/data2/mlfDL/FACE/detectron2/configs/X-101-32x8d.pkl"
  WEIGHTS: ""
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
SOLVER:
  STEPS: (100000, 150000)
  MAX_ITER: 200000
  IMS_PER_BATCH: 8
  BASE_LR: 0.01