def construct_name2id_map():
    db_id_to_name_map = {
        -3: "color doppler horizontal transverse plane of upper abdomen",
        -7: "color doppler four-chamber heart plane",
        -10: "color doppler right ventricular outflow tract plane",
        -14: "color doppler three-vessel and tracheal plane",
        -11: "color doppler plane of placental umbilical cord insertion",
        -15: "color doppler left ventricular outflow tract plane",
        -17: "color doppler transverse plane of umbilical cord abdominal wall insertion",
        -29: "color doppler coronal plane of bilateral kidneys",
        -30: "color doppler short-axis plane of cardiac base",
        -31: "color doppler three-vessel plane",
        -16: "coronal plane of tibia and fibula (1)",
        -18: "coronal plane of ulna and radius (1)",
        -100: "femur long-axis plane (1)",
        -101: "humerus long-axis plane (1)",
        -33: "foot plantar plane (1)",
        -36: "color doppler bifurcation plane of left and right pulmonary arteries",
        -39: "color doppler long-axis plane of superior and inferior vena cava",
        -42: "color doppler long-axis plane of aortic arch",
        -43: "color doppler long-axis plane of arterial duct arch",
        -148: "color doppler four-chamber heart plane end systole",
        -149: "color doppler four-chamber heart plane end diastole",
        0: 'unknown',
        1: 'others',
        2: "thalamic transverse plane",
        3: "horizontal cross-section of upper abdomen",
        4: "long-axis plane of the femur or humerus",
        5: "cerebellar transverse plane",
        6: "sagittal plane of lumbosacral coccygeal spine and cervicothoracic spine",
        7: "four-chamber heart plane",
        8: "horizontal transverse plane of bilateral eyeballs",
        9: "transverse plane of bilateral kidneys",
        10: "right ventricular outflow tract plane",
        11: "plane of placental umbilical cord insertion",
        12: "nasolabial coronal plane",
        13: "lateral ventricular transverse plane",
        14: "three-vessel and tracheal plane",
        15: "left ventricular outflow tract plane",
        16: "coronal plane of tibia and fibula",
        17: "transverse plane of umbilical cord abdominal wall insertion",
        18: "coronal plane of ulna and radius",
        19: "fetal NT plane",
        20: "fetal crown-rump length measurement plane",
        21: 'coronal plane of diaphragm',
        22: 'facial median sagittal plane',
        23: 'sagittal plane of left diaphragm',
        24: 'sagittal plane of right diaphragm',
        25: 'sagittal plane of cervical internal os',
        26: 'color doppler transverse plane of urinary bladder',
        27: 'sagittal plane of left kidney',
        28: 'sagittal plane of right kidney',
        29: 'coronal plane of bilateral kidneys',
        30: 'short-axis plane of cardiac base',
        40: 'long-axis plane of forearm',
        41: 'long-axis plane of calf',
        31: 'three-vessel plane',
        32: 'coronal plane of palm',
        33: 'foot plantar plane',
        34: 'sagittal plane of calf',
        35: 'facial coronal plane',
        36: 'bifurcation plane of left and right pulmonary arteries',
        37: 'plantar plane of bilateral feet',
        39: "long-axis plane of superior and inferior vena cava",
        42: "long-axis plane of aortic arch",
        43: "long-axis plane of arterial duct arch",
        100: "femur long-axis plane",
        101: "humerus long-axis plane",
        102: "sagittal plane of cervicothoracic spine",
        103: "sagittal plane of lumbosacral coccygeal spine",
        104: 'transverse plane of gallbladder level',
        105: "sagittal plane of middle spine segment",
        106: "sagittal plane of entire spine",
        112: 'partial cardiac plane',
        113: 'cranial plane',
        114: 'coronal plane of ulna radius and coronal plane of tibia fibula',
        115: 'upper abdomen and gallbladder level transverse plane',
        116: 'sagittal plane of kidney and diaphragm',
        117: 'coronal plane of kidney and diaphragm',
        118: 'coronal plane of palm and foot plantar plane',
        119: '11 cardiac cycle planes',
        120: "transverse plane of upper alveolus",
        121: 'coronal plane of ulna radius, coronal plane of tibia fibula and sagittal plane of calf',
        130: 'oblique coronal plane of soft palate',
        131: 'oblique coronal plane of hard palate',
        132: 'cleft lip-nasolabial coronal plane',
        133: 'cleft palate-soft palate oblique coronal plane',
        134: 'cleft palate-hard palate oblique coronal plane',
        135: 'abdomen gallbladder umbilical cord plane',
        136: 'second and third trimester cranial coronal and sagittal plane',
        137: 'median sagittal plane of cranium',
        138: 'parasagittal plane of cranium',
        139: 'sagittal plane of cranial cerebral hemisphere',
        140: 'coronal plane of cranium through anterior horn of lateral ventricle',
        141: 'coronal plane of cranium through body of lateral ventricle',
        142: 'coronal plane of cranium through trigone and posterior horn of lateral ventricle',
        143: 'coronal plane of cranium through frontal lobe',
        144: 'coronal plane of cranium through occipital lobe',
        145: 'coronal plane of cranium through cerebellum',
        146: 'cranial vault transverse plane',
        147: 'fan-shaped region',
        148: "four-chamber heart plane end systole",
        149: "four-chamber heart plane end diastole",
        1000: 'amniotic fluid measurement plane',
        1001: 'placental measurement plane',
        1002: 'cranial measurement plane',
        1003: 'spine measurement plane',
        1004: 'spectral measurement plane',
        1005: "middle cerebral artery blood flow spectrum",
        1006: "umbilical artery blood flow spectrum",
        -10000: 'dual view image',
        -10001: 'quad view image',
        -10002: 'spectral image'
    }

    name_to_db_id_map = {
        plane_name: plane_id for plane_id, plane_name in db_id_to_name_map.items()
    }

    db_id_to_name_map[-1] = 'unknown'

    return name_to_db_id_map, db_id_to_name_map
